### PR TITLE
adding functional docker implementation and how-to

### PR DESCRIPTION
**Pull request by jwdinius**
I have bundled all dependencies in a Dockerfile in a hope that someone else can use it.  Check the how-to for instructions and verification details.

### CODE REVIEW

**Comment by pengsida** [comment]
Wow, your docker file is so cool and helpful.
I find that `build_ceres.sh` and `build_extend_utils_cffi.py` have been revised to adapt the docker configuration.
How about adding the docker version for the two files like `build_ceres_for_docker.sh` and `build_extend_utils_cffi_for_docker.py`? Since the original contents in the two files are necessary for the current configuration.

**Comment by jwdinius** [comment]
@pengsida Great idea!  I will update with your suggestions.

**Comment by jwdinius** [comment]
@pengsida, I've implemented the changes.

**Comment by pengsida** [comment]
I have updated merged the codes and added the relavent instructions in the readme: https://github.com/zju3dv/pvnet#installation
Thank you very much!

**Pull request merged**
